version: '3'

services:
  cloud_sql_prod:
    image: mysql:latest
    container_name: cloud_sql_prod_container
    command: ["sh", "-c", "exec mysql -h <public-ip-sql-prod> -P 3306 -u <prod_cloud_sql_user> -p<prod_cloud_sql_password>"]
    ports:
      - "3306:3306"
    depends_on:
      - stg_mysql

  cloud_sql_stg:
    image: mysql:latest
    container_name: cloud_sql_stg_container
    command: ["sh", "-c", "exec mysql -h <public-ip-sql-stg> -P 3307 -u <stg_cloud_sql_user> -p<stg_cloud_sql_password>"]
    ports:
      - "3307:3307"
    depends_on:
      - prod_mysql

networks:
  default:
    external:
      name: bridge
