version: '3'

services:
  prod_mysql:
    image: mysql:latest
    container_name: prod_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: prod_root_password
      MYSQL_DATABASE: prod_database
      MYSQL_USER: prod_user
      MYSQL_PASSWORD: prod_password
    ports:
      - "3306:3306"

  stg_mysql:
    image: mysql:latest
    container_name: stg_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: stg_root_password
      MYSQL_DATABASE: stg_database
      MYSQL_USER: stg_user
      MYSQL_PASSWORD: stg_password
    ports:
      - "3307:3306"

